<?php

namespace sil13\VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @param $str
     * @return array Renvoi les articles ayant $str dans le nom.
     */
    public function findArticlesLikeName($str) {

        $query = $this->getEntityManager()->createQuery("SELECT article FROM sil13VitrineBundle:Article article WHERE article.name LIKE :searchterm")
                        ->setParameter('searchterm', '%'.$str.'%');

        return $query->getResult();
    }
}
