<?php

namespace sil13\VitrineBundle\Repository;

/**
 * BuyOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
