admin_buyorder_index:
    path:     /
    defaults: { _controller: "sil13AdminBundle:BuyOrder:index" }
    methods:  GET

admin_buyorder_show:
    path:     /{id}/show
    defaults: { _controller: "sil13AdminBundle:BuyOrder:show" }
    methods:  GET

admin_buyorder_new:
    path:     /new
    defaults: { _controller: "sil13AdminBundle:BuyOrder:new" }
    methods:  [GET, POST]

admin_buyorder_edit:
    path:     /{id}/edit
    defaults: { _controller: "sil13AdminBundle:BuyOrder:edit" }
    methods:  [GET, POST]

admin_buyorder_delete:
    path:     /{id}/delete
    defaults: { _controller: "sil13AdminBundle:BuyOrder:delete" }
    methods:  DELETE
