sil13\VitrineBundle\Entity\OrderLine:
    type: entity
    table: null
    repositoryClass: sil13\VitrineBundle\Repository\OrderLineRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        count:
            type: integer
            length: 5
        price:
            type: integer
            length: 4
    manyToOne:
        article:
            mappedBy: orderLines
            targetEntity: sil13\VitrineBundle\Entity\Article
        buyOrder:
            inversedBy: orderLines
            targetEntity: sil13\VitrineBundle\Entity\BuyOrder
    lifecycleCallbacks: {  }
